### ISSUE TITLE
File upload metadata and error messages

### ISSUE THREAD

**Issue by Ajax23** [AUSSDA/pyDataverse#20]
When uploading a file, it should be possible to add metadata to the file. 

Also a feedback could be given, wether a file already exists with the same checksum. (Should there be an option to force overwriting the file?)

**Comment by skasberger** [comment]
For the next release, I have to look a bit deeper into the handling of Datafiles. This was implemented bit fast at the end, and have not tested out the full functionality of the endpoints, of Dataverses use of Datafiles and its metadata. 

added functionality:
* add `overwrite` attribute
* check if datafile already exists 
* add metadata to the file upload

**Comment by skasberger** [comment]
The functionality was already implemented, and improved in https://github.com/AUSSDA/pyDataverse/commit/7142110bae8632426cc05f12680bf30e466cf67b.
