### ISSUE TITLE
query_str vs path

### ISSUE THREAD

**Issue by pdurbin** [AUSSDA/pyDataverse#22]
The first argument to many functions is `query_str` but maybe it should be `path` instead. This tripped me up a little. Here's the doc I was reading for v0.2.1:

<img width="683" alt="Screen Shot 2019-06-26 at 6 09 14 AM" src="https://user-images.githubusercontent.com/21006/60171665-0ccd7680-97d9-11e9-8c4f-38dd83f71105.png">

Here's a reference on query strings vs path from https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Examples

<img width="793" alt="Screen Shot 2019-06-26 at 6 01 25 AM" src="https://user-images.githubusercontent.com/21006/60171077-de9b6700-97d7-11e9-9f93-360ca1ae9fa0.png">

It looks like I used the word "endpoint" instead of "path" here:

https://github.com/IQSS/dataverse-sample-data/blob/4c85a6a43cca17b274e4f6ed18ca909c3cc761d3/get_api_token.py#L9

    endpoint = '/builtin-users/' + username + '/api-token'
    resp = api.get_request(endpoint, params=params, auth=True)

So maybe "path" or "endpoint"? To me, "query string" has a specific meaning. It's the key/value pairs after the "?" like `tag=networking&order=newest` in the example above.

**Comment by skasberger** [comment]
Thanks, you are right. This should be changed for consistency and correctness. Will add it to the next release.
