### ISSUE TITLE
Create dataset with existing DOI

### ISSUE THREAD

**Issue by RightInTwo** [AUSSDA/pyDataverse#3]
Afaik, at the current state (for me it's 4.11), DDI XML is the only way to get existing DOIs into Dataverse. Therefore this functionality would be very useful. I guess it's just the :importddi that would need to be added.

**Comment by skasberger** [comment]
Thanks for the input. As far as I know, DDI 2.5 XML works in a new release (guess 4.11 is right then). My idea is, to convert the internal datastructure in all kind of output formats. Different DDI XML versions are on top of the lists, but need to dive a bit into it, cause i am not really used to DDI. 

Will add the outcome here, when I did some research about the issue.

**Comment by skasberger** [comment]
So, this are two different issues: 

* get existing doi into dataverse via api request
* import/export DDI XML ([#18](https://github.com/AUSSDA/pyDataverse/issues/18))

**Comment by RightInTwo** [comment]
@skasberger yes. and it would be very nice if that functionality would be accessible independent of the metadata format - it is of course not the objective of pyDataverse to provide a workaround for issues in the core project....

**Comment by skasberger** [comment]
@RightInTwo you mean, that it is possible to convert from DDI XML to Dataverse metadata JSON, and reverse?

**Comment by skasberger** [comment]
* API Docs
  * http://guides.dataverse.org/en/latest/api/native-api.html#create-a-dataset-in-a-dataverse
  * http://guides.dataverse.org/en/latest/api/native-api.html#import-a-dataset-into-a-dataverse
* Mailinglist Discussion: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/dataverse-community/uQqWyMAx0X4/N4IT3o3_BgAJ

**Comment by skasberger** [comment]
Closed in https://github.com/AUSSDA/pyDataverse/commit/d954619485b16ec3cf826bb7786893a1e01a0c10
