### ISSUE TITLE
support "Show Contents of a Dataverse" (`/api/dataverses/$id/contents`)

### ISSUE THREAD

**Issue by pdurbin** [AUSSDA/pyDataverse#31]
Please support the "Show Contents of a Dataverse" API.

At http://guides.dataverse.org/en/4.15/api/native-api.html#show-contents-of-a-dataverse it is documented like this:

> Lists all the DvObjects under dataverse id.
> 
> `GET http://$SERVER/api/dataverses/$id/contents`

As a workaround for now I'm using api.get_request: https://github.com/IQSS/dataverse-sample-data/blob/ed52c316f530229b0c40463dc18c5f16d07cf11d/destroy_all_dvobjects.py#L30

**Comment by skasberger** [comment]
Implemented in https://github.com/AUSSDA/pyDataverse/commit/10bb74a4452ee532b0fd242b5a2d4814d8ef25ec.
