### ISSUE TITLE
Support jsonData when adding a file to a dataset (api.upload_file)

### ISSUE THREAD

**Issue by pdurbin** [AUSSDA/pyDataverse#32]
The example at http://guides.dataverse.org/en/4.15/api/native-api.html#add-a-file-to-a-dataset illustrates that `jsonData` can be uploaded when adding a file:

`curl -H "X-Dataverse-key:$API_TOKEN" -X POST -F 'file=@data.tsv' -F 'jsonData={"description":"My description.","directoryLabel":"data/subdir1","categories":["Data"], "restrict":"true"}' "https://example.dataverse.edu/api/datasets/:persistentId/add?persistentId=$PERSISTENT_ID"`

The `jsonData` object allows the user to add additional metadata about the file:

- description
- file hierarchy ("directoryLabel")
- tags ("categories")

It would be great if `api.upload_file` supported this `jsonData` object.

**Comment by pdurbin** [comment]
Here's a real world use case: https://github.com/IQSS/dataverse-sample-data/issues/5

**Comment by skasberger** [comment]
Partly implemented here: https://github.com/AUSSDA/pyDataverse/commit/ebdba4d3e52b62a02c2f50296d4b6cbeab9b36f8
