### ISSUE TITLE
support "Getting File Metadata" and "Updating File Metadata" API endpoints

### ISSUE THREAD

**Issue by pdurbin** [AUSSDA/pyDataverse#33]
Support for the following APIs would be appreciated:

- Getting File Metadata: http://guides.dataverse.org/en/4.15/api/native-api.html#getting-file-metadata
- Updating File Metadata: http://guides.dataverse.org/en/4.15/api/native-api.html#updating-file-metadata

**Comment by skasberger** [comment]
Implemented in 
* https://github.com/AUSSDA/pyDataverse/commit/035bdabd980189c5217a0155deae215c8c83e596
* https://github.com/AUSSDA/pyDataverse/commit/ebdba4d3e52b62a02c2f50296d4b6cbeab9b36f8

Still in develop branch, but will be released later this year.
