### ISSUE TITLE
API token is not sent when get_datafile() is called

### ISSUE THREAD

**Issue by martinec** [AUSSDA/pyDataverse#38]
The function `get_datafile()` is using the following call to `get_request()`

https://github.com/AUSSDA/pyDataverse/blob/87d82eaaca5a120f98ac428b1d3efc34954e13ca/src/pyDataverse/api.py#L949

As `auth` is by default `False` when calling `get_request(query_str, params=None, auth=False)` the API token is not being sent and the server may return a `403` error. 

The same behavior could be noticed by calling `get_dataset_export()`, `get_datafiles()`, `get_datafile_bundle()`, ...

Other functions like `get_dataverse()` work as expected by using `get_request()` with the extra `auth` parameter:

https://github.com/AUSSDA/pyDataverse/blob/87d82eaaca5a120f98ac428b1d3efc34954e13ca/src/pyDataverse/api.py#L357 

Is there any workaround besides changing `auth=True`  in the  `get_request()` definition?

Environment:
```
pyDataverse==0.2.1
requests==2.22.0
urllib3==1.25.7
```

**Comment by skasberger** [comment]
Thanks for the issue.

I have added the auth flag to all remaining functions, where it was missing. You can find it in the develop branch (https://github.com/AUSSDA/pyDataverse/commit/b03d3066b9d774a2d1d9a0e4f808a23f75247c64) . Now you can easily pipe the auth value through. Thanks again for the hint.
