### ISSUE TITLE
A closing bracket is missing in the Developer Interface

### ISSUE THREAD

**Issue by BPeuch** [AUSSDA/pyDataverse#40]
On [this page](https://pydataverse.readthedocs.io/en/latest/developer.html#pyDataverse.api.Api.create_dataset), right here:

![missing_bracket](https://user-images.githubusercontent.com/15209224/75903384-c9d0a200-5e41-11ea-89cc-e7ddafe06725.png)

Just a detail, but you know what they say: that's where God and the Devil are!

**Comment by skasberger** [comment]
Thx. Will be part of the next release.
