### ISSUE TITLE
Coordinate GDCC/dvcli and pyDataverse

### ISSUE THREAD

**Issue by poikilotherm** [AUSSDA/pyDataverse#52]
Hi @skasberger,

for [GDCC/dvcli](https://github.com/GlobalDataverseCommunityConsortium/dvcli) I want to make heavy use of your great library.

As I wrote some comments to other issues already, I wonder if we should talk about the scope of your library. It doesn't make much sense to implement things in dvcli and then here again or the other way round.

I would be happy to either contribute here or give you access to the dvcli project.
If you would prefer talking over writing, hit me :smile:

**Comment by skasberger** [comment]
Yeah, let's do a call about this. As a move of the GitHub repository from AUSSDA to GDCC is also part of the plan for the next release, this would fit great. 

Going a little bit into the issue: i do not have experience in developing cli tools, so I don't know, how a python tool could fit into that. I was already thinking of extending pyDataverse with a cli functionality. In general I would recommend, meet somewhere and move on together. No one needs two tools developed in parallel with partly complementary, partly overlapping functionalities. 

I am very flexible right now, so hit me via Email and suggest an appointment.

**Comment by skasberger** [comment]
Done: https://github.com/gdcc/pyDataverse
