### ISSUE TITLE
Add to jenkins.dataverse.org

### ISSUE THREAD

**Issue by pdurbin** [AUSSDA/pyDataverse#6]
https://jenkins.dataverse.org is a new service being offered to the Dataverse community for automated testing, continuous integration and perhaps any other use you can dream up. 😄 

For more about this Jenkins service, please see http://guides.dataverse.org/en/4.14/developers/testing.html#continuous-integration

I'm very glad to see that Travis tests are already set up for pyDataverse at https://travis-ci.com/AUSSDA/pyDataverse

I am **not** suggesting that we replace Travis with Jenkins. Rather, I'm suggesting a "belt and suspenders" approach. In fact, for Dataverse itself we are currently using Travis to know if our Java code even compiles (and if the unit tests pass) and Jenkins to know if our API test suite is passing.

The way to add pyDataverse is to talk to me and @donsizemore at http://chat.dataverse.org (we're both in the eastern timezone of the United States and don't work weekends 😛 ). We'll get the test suite passing (with help from @skasberger probably) and then add it as a job to https://github.com/IQSS/dataverse-jenkins . Actually, once I talk to Don I'll probably create an issue over in that issue tracker for adding the job definition (XML, I believe).

**Comment by pdurbin** [comment]
A job has been set up at https://jenkins.dataverse.org but the config hasn't been added to the dataverse-jenkins repo so I just opened https://github.com/IQSS/dataverse-jenkins/issues/12

**Comment by skasberger** [comment]
Thanks @pdurbin. As we now have our own Jenkins instance at AUSSDA, I will do this there.
