### ISSUE TITLE
error while import pyDataverse.api

### ISSUE THREAD

**Issue by moumenuisawe** [AUSSDA/pyDataverse#7]
hello, 
when i try to import API using this line of code 
`from pyDataverse.api import Api`
there is some error occurred

`Traceback (most recent call last):
  File "C:/Users/MIsawe/PycharmProjects/untitled/main.py", line 1, in <module>
    from pyDataverse.api import Api
  File "C:\Users\MIsawe\PycharmProjects\untitled\venv\lib\site-packages\pyDataverse\__init__.py", line 6, in <module>
    from requests.packages import urllib3
ModuleNotFoundError: No module named 'requests'
`

**Comment by TomMiksa** [comment]
This has nothing to do with the pyDataverse.api. You're missig modules. Add them to your environment.
https://urllib3.readthedocs.io/en/latest/

'pip install urllib3'

**Comment by skasberger** [comment]
@moumenuisawe Thanks for your issue. How did you install pyDataverse (via pip install pyDataverse or from the GitHub repo)??

**Comment by moumenuisawe** [comment]
using pip

**Comment by skasberger** [comment]
fixed this in release [0.1.1](https://github.com/AUSSDA/pyDataverse/releases/tag/v0.1.1).
